#!/bin/bash
#PBS -q copyq
#PBS -l software=python
#PBS -l mem=50MB
#PBS -l walltime=5:00:00

set -e

## Run the ECMWF update for the ERA-Interim dataset.
## Check monthly, although the dataset is produced quarterly.
## This file fetches .grib format, as the matlab code already parses that.
## A netcdf version was written for testing, but is not used.

module load python

cd /g/data1/xc0/original/TimeSeries/Climate/ERA-Interim/ecmwf
python ~/job-scheduler/ecmwfGetEraIntGrib.py
