#!/bin/bash
#PBS -P xc0
#PBS -q copyq
#PBS -l other=gdata1
#PBS -l software=python
#PBS -l mem=50MB
#PBS -l walltime=2:00:00
#PBS -l jobfs=1GB
#PBS -l wd
#
## Run the ECMWF update for the TIGGE dataset.

module load python
module load gdal/1.11.1-python
# makes "import ecmwfapi" work
export PYTHONPATH=$PATHONPATH:~/job-scheduler

cd /g/data/xc0/original/TimeSeries/Climate/Forecasts/ECMWF/
python ~/job-scheduler/ecmwfGetTiggeGrib.py

