#!/bin/bash 
#PBS -P xc0 
#PBS -q normal
#PBS -l walltime=3:00
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l software=python
# specify other software requirements?

module load python/2.7.5
module load python/2.7.5-matplotlib
module load geos
module load intel-cc/12.1.9.293
#module load gtk/2.24.21

export PYTHONPATH=$PATHONPATH:/short/xc0/python-modules/lib/python

python plotmap.py \
	-i /short/xc0/zjh157/apwm/maps/global/nc \
	-o /g/data1/ub8/apwm/APWM/latest \
	-l info

